### ISSUE TITLE
any success with stamped messages?

### ISSUE THREAD

**Issue by wegunterjr** [SynapseProgramming/ros2labview_guide#1]
We are trying to do a stamped message and can generate it in LabVIEW, and we can see it in ROS2, but there are some issues with the header data not being filled out correctly:

```
2. - AckermannDriveStamped
3a. -- Header
     - uint32 seq
     - time stamp
     - string frame_id

3b. -- AckermannDrive
    float32 steering_angle
    float32 steering_angle_velocity
    float32 speed
    float32 acceleration
    float32 jerk
```
But this is our output.   No sequence, time stamp is strange too... 
Is it QOS maybe?
```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
drive:
  steering_angle: 1.401298464324817e-45
  steering_angle_velocity: 0.0
  speed: 0.0
  acceleration: 0.0
  jerk: 0.0
```
